name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:

  check-manifest:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.7
        - name: Check Python manifest completeness
          run: |
            python -m pip install --upgrade pip setuptools py wheel
            pip install -e .[tests]
            ./run-tests.sh --check-manifest

  docs-sphinx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip setuptools py wheel
          pip install -e .[postgresql,elasticsearch7,docs]
      - name: Run Sphinx documentation with doctests
        run: ./run-tests.sh --check-sphinx

  python-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          python-version: [3.6, 3.7, 3.8]
          services: [release, lowest]
          include:
          - services: release
            SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://invenio:invenio@localhost:5432/invenio"
            POSTGRESQL_VERSION: POSTGRESQL_12_LATEST
            ES_VERSION: "ES_7_LATEST"
            REQUIREMENTS: "release"
            REQUIREMENTS_LEVEL: "pypi"

          - services: lowest
            SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://invenio:invenio@localhost:5432/invenio"
            POSTGRESQL_VERSION: POSTGRESQL_9_LATEST
            ES_VERSION: "ES_6_LATEST"
            REQUIREMENTS: "lowest"
            REQUIREMENTS_LEVEL: "min"
    env:
      SQLALCHEMY_DATABASE_URI: ${{matrix.SQLALCHEMY_DATABASE_URI}}
      POSTGRESQL_VERSION: ${{matrix.POSTGRESQL_VERSION}}
      ES_VERSION: ${{matrix.ES_VERSION}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Generate dependencies
        run: |
          python -m pip install --upgrade pip setuptools py twine wheel coveralls requirements-builder
          requirements-builder -e all,postgresql,elasticsearch7 --level=${{matrix.REQUIREMENTS_LEVEL}} setup.py > .${{matrix.REQUIREMENTS}}-requirements.txt
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('.${{matrix.REQUIREMENTS}}-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          pip install -r .${{matrix.REQUIREMENTS}}-requirements.txt
          pip install -e .[all]
          pip freeze
          docker --version
          docker-compose --version
      - name: Run tests
        run: |
          ./run-tests.sh --check-pytest
