# -*- coding: utf-8 -*-
#
# Copyright (C) 2022 Graz University of Technology.
#
# Invenio-RDM-Records is free software; you can redistribute it and/or modify
# it under the terms of the MIT License; see LICENSE file for more details.

name: i18n:extract,push,pull translations
on:
  push:
    branches:
      - main

jobs:
  translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # extract
      - name: extract_messages
        run: |
          python setup.py extract_messages

      # install transifex client
      - name: transifex-client
        run: |
          pip install transifex-client

      # store token
      - name: store token
        run: |
          tx init --token ${{ secrets.TRANS_TOKEN }} --force --no-interactive

      # push
      - name: push_messages
        run: |
          tx push -s -t
  
      # pull all lang
      - name: pull translations
        run: |
          tx pull -a

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: i18n:extract,push,pull translations
          title: i18n:extract,push,pull translations
          body: i18n:extract,push,pull translations
          branch: 101-translations  # name of branch which PR is created from
          delete-branch: true  # delete branch once merged,closed
